# Generated by Django 3.2.9 on 2022-01-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220129_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='payed_for',
        ),
    ]
