# Generated by Django 3.2.9 on 2022-02-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_payed_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='endDate',
        ),
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='expectedLength',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
