# Generated by Django 3.2.9 on 2022-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220202_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expectedLength',
        ),
        migrations.AddField(
            model_name='project',
            name='expectedLength',
            field=models.DurationField(),
        ),
    ]
