# Generated by Django 3.2.9 on 2022-02-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_rename_project_update_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='examplePrice_longterm',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='examplePrice_midterm',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='examplePrice_shortterm',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
