# Generated by Django 3.2.9 on 2022-01-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220121_2042'),
        ('checkout', '0002_auto_20220121_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commision',
            new_name='Commission',
        ),
    ]
