# Generated by Django 3.2.9 on 2022-01-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220121_2042'),
        ('checkout', '0004_auto_20220121_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commItem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
