# Generated by Django 3.2.9 on 2022-01-21 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220121_2042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0005_alter_commission_commitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='commItem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project'),
        ),
    ]
