# Generated by Django 3.2.9 on 2022-01-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20220121_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='user',
        ),
    ]
