# Generated by Django 3.2.9 on 2022-01-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_commission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
