# Generated by Django 3.2.9 on 2022-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_commission_commitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
    ]
